version: '3'
services:
  web:
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/baby
    ports:
      - 8000:8000
      - 5678:5678

  redis:
    image: redis:latest

  celery_worker:
    build: .
    env_file:
      - ./.env
    command: celery -A baby worker -l info
    volumes:
      - .:/baby
    depends_on:
      - redis
