# Generated by Django 4.2.5 on 2023-09-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("babies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="baby",
            name="feeding_interval",
            field=models.IntegerField(default=60),
        ),
    ]
